# Generated by Django 5.0.1 on 2024-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
